volumes:
  fastify-vol:
    driver: local
    name: fastify-vol
#     driver_opts:
#       type: none
#       o: bind
#       device: ${NGINX_VOL}

networks:
  internal:
    driver: bridge
    name: internal
  external:
    driver: bridge
    name: external

services:
  fastify:
    build:
      context: ./fastify-nodejs
      dockerfile: Dockerfile
    container_name: fastify
    image: node:14
    hostname: fastify
    volumes:
      - fastify-vol:/usr/src/app
    working_dir: /usr/src/app
    restart: unless-stopped
    networks:
      - internal
    dns:
      - 127.0.0.11
