volumes:
  fastify-vol:
    driver: local
    name: fastify-vol
#     driver_opts:
#       type: none
#       o: bind
#       device: ${NGINX_VOL}

networks:
  internal:
    driver: bridge
    name: internal
  backend:
    driver: bridge
    name: backend

services:
  fastify:
    build:
      context: ./fastify-nodejs
      dockerfile: Dockerfile
    container_name: fastify
    hostname: fastify
    volumes:
      - fastify-vol:/usr/src/app
    # working_dir: /usr/src/app
    restart: unless-stopped
    networks:
      - internal
      - backend
    labels:
      - "traefik.http.routers.fastify.rule=Host(`fastify.local`)"
      - "traefik.http.routers.fastify.entrypoints=websecure"
      - "traefik.http.services.fastify.loadbalancer.server.port=3000"