volumes:
  front-end-vol:
    driver: local
    name: front-end-vol
    # driver_opts:
    #   type: bind
    #   o: bind
    #   device: ./

# networks:
#   backend:
#     external: true

services:
  front-end:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DNS_SERVER=8.8.8.8
    container_name: front-end
    hostname: front-end
    volumes:
      - front-end-vol:/usr/src/app
    # working_dir: /usr/src/app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DOMAIN: ${DOMAIN}
      IP: ${IP}
      DOMAIN_TEST: ${DOMAIN_TEST}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      # Router for canonical domain requests (highest priority)
      - "traefik.http.routers.front-end.rule=Host(`front-end.${DOMAIN}`)"
      - "traefik.http.routers.front-endl.entrypoints=websecure"
