secrets:
  ssl_key.key:
    file: ${SSL_KEY}
  ssl_crt.crt:
    file: ${SSL_CRT}
  ssl_pem:
    file: ${SSL_PEM}
  ssl_email:
    file: ${SSL_EMAIL}

networks:
  frontend:
    driver: bridge
    name: frontend
  backend:
    driver: bridge
    name: backend

volumes:
  traefik-logs:
    driver: local
    name: traefik-vol
    driver_opts:
      type: bind
      o: bind
      device: ${TRAEFIK_VOL}


services:
  traefik:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: "traefik:v3.3"
    container_name: traefik
    hostname: traefik
    environment:
      DOMAIN: ${DOMAIN}
      DOMAIN_TEST: ${DOMAIN_TEST}
      HOST_USER: ${HOST_USER}
      SSL_PORT: ${SSL_PORT}
      DNS_SERVER: ${DNS_SERVER}
      DNS_SEARCH: ${DNS_SEARCH}
      IP: ${IP}
      TZ: Europe/Berlin
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    dns:
      - ${DNS_SERVER}
    dns_search:
      - ${DNS_SEARCH}
    extra_hosts:
      - "${DOMAIN}:127.0.0.1"
      - "${DOMAIN}:${IP}"
    secrets:
      - ssl_key.key
      - ssl_crt.crt
      - ssl_pem
      - ssl_email
    volumes:
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      # - "./dynamic/config.yml:/etc/traefik/etc/traefik/config.yml:ro"
      - "traefik-logs:/etc/traefik/"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    command:
      - "traefik"
      - "--providers.file.filename=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--log.level=DEBUG"
    #   - "--entryPoints.web.address=:80"
    #   - "--entryPoints.websecure.address=:443"
    #   - "--entryPoints.websecure.http.tls=true"
    #   - "--entryPoints.websecure.http.tls.certResolver=myresolver"
    #   - "--entryPoints.websecure.http.tls.domains[0].main=${DOMAIN}"
    #   - "--entryPoints.websecure.http.tls.domains[0].sans=${IP}"
    # labels:
    #   - traefik.enable=true
    #   - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) || Host(`${IP}`)"
    #   - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
    #   - "--certificatesResolvers.myresolver.acme.email=${SSL_EMAIL}"
    #   - "--certificatesResolvers.myresolver.acme.storage=/etc/traefik/acme.json"
    #   - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
    #   - "--entryPoints.websecure.http.tls.certificates[0].certFile=/run/secrets/ssl_crt"
    #   - "--entryPoints.websecure.http.tls.certificates[0].keyFile=/run/secrets/ssl_key"
