secrets:
  ssl_key.key:
    file: ${SSL_KEY}
  ssl_crt.crt:
    file: ${SSL_CRT}
  ssl_pem:
    file: ${SSL_PEM}
  ssl_email:
    file: ${SSL_EMAIL}

# networks:
#   backend:
#     external: true
#   frontend:
#     external: true

volumes:
  traefik-logs:
    driver: local
    name: traefik-vol
    driver_opts:
      type: bind
      o: bind
      device: ${TRAEFIK_VOL}


services:
  traefik:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: "traefik:v3.3"
    container_name: traefik
    hostname: traefik
    environment:
      DOMAIN: ${DOMAIN}
      DOMAIN_TEST: ${DOMAIN_TEST}
      HOST_USER: ${HOST_USER}
      SSL_PORT: ${SSL_PORT}
      DNS_SERVER: ${DNS_SERVER}
      DNS_SEARCH: ${DNS_SEARCH}
      IP: ${IP}
      TZ: Europe/Berlin
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    dns:
      - ${DNS_SERVER}
      - 127.0.0.1
    dns_search:
      - ${DNS_SEARCH}
    dns_opt:
      - "port=5053"  # Port for local DNS server
    extra_hosts:
      - "${DOMAIN}:127.0.0.1"
      - "${DOMAIN}:${IP}"
    #   - "${DOMAIN_TEST}:127.0.0.1"
    #   - "${DOMAIN_TEST}:${IP}"
    secrets:
      - ssl_key.key
      - ssl_crt.crt
      - ssl_pem
      - ssl_email
    volumes:
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
    #   - "./config/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro"
      - "traefik-logs:/etc/traefik/"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    command:
      - "traefik"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
    # labels:
    #   - traefik.enable=true
    #   - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) || Host(`${IP}`) || Host(`127.0.0.1`)"  # Updated domain address
    #   - "traefik.http.routers.traefik.entrypoints=web,websecure"
    #   - "traefik.http.routers.traefik.middlewares=redirect-to-newdomain@file"
