secrets:
  ssl_key.key:
    file: ${SSL_KEY}
  ssl_crt.crt:
    file: ${SSL_CRT}
  ssl_pem.pem:
    file: ${SSL_PEM}
  ssl_email:
    file: ${SSL_EMAIL}

volumes:
  traefik-logs:
    driver: local
    name: traefik-vol
    # driver_opts:
    #   type: bind
    #   o: bind
    #   device: ./


services:
  traefik:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        IP: ${IP}
        DOMAIN_TEST: ${DOMAIN_TEST}
      secrets:
      - ssl_key.key
      - ssl_crt.crt
      - ssl_pem.pem
      - ssl_email
    # image: "traefik:v3.3"
    image: img_traefik:latest
    container_name: traefik
    hostname: traefik
    environment:
      DOMAIN: ${DOMAIN}
      DOMAIN_TEST: ${DOMAIN_TEST}
      HOST_USER: ${HOST_USER}
      SSL_PORT: ${SSL_PORT}
    #   DNS_SERVER: ${DNS_SERVER}
    #   DNS_SEARCH: ${DNS_SEARCH}
      IP: ${IP}
      TZ: Europe/Berlin
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # dns:
    #   - ${DNS_SERVER}
    #   - 127.0.0.1
    # dns_search:
    #   - ${DNS_SEARCH}
    # dns_opt:
    #   - "port=5053"  # Port for local DNS server
    extra_hosts:
      - "${DOMAIN}:127.0.0.1"
      - "${DOMAIN}:${IP}"
    secrets:
      - ssl_key.key
      - ssl_crt.crt
      - ssl_pem.pem
      - ssl_email
    volumes:
      - "${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro"
      - "traefik-logs:/etc/traefik/"
    networks:
      - frontend
      - backend
      # - game # will handle wss?
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.http-catchall.rule=Host(`${DOMAIN}`) || Host(`${IP}`) || Host(`127.0.0.1`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # Middleware to redirect to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Redirect HTTPS to canonical domain
      - "traefik.http.routers.https-catchall.rule=Host(`${IP}`) || Host(`127.0.0.1`)"
      - "traefik.http.routers.https-catchall.entrypoints=websecure"
      - "traefik.http.routers.https-catchall.middlewares=redirect-to-canonical"
      # Middleware to redirect to canonical domain
      - "traefik.http.middlewares.redirect-to-canonical.redirectregex.regex=^https?://(?:${IP}|127\\.0\\.0\\.1)(.*)"
      - "traefik.http.middlewares.redirect-to-canonical.redirectregex.replacement=https://${DOMAIN}$$1"
      - "traefik.http.middlewares.redirect-to-canonical.redirectregex.permanent=true"
      # Main router for the canonical domain
      - "traefik.http.routers.main.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.main.entrypoints=websecure"
      - "traefik.http.routers.main.tls=true"

      # - "traefik.http.routers.https-redirect.rule=Host(`${DOMAIN}`) || Host(`${IP}`) || Host(`127.0.0.1`)"
      # - "traefik.http.routers.https-redirect.entrypoints=websecure"
      # - "traefik.http.routers.https-redirect.middlewares=redirect-to-canonical"
      # - "traefik.http.routers.https-redirect.service=noop-service"

      # - "traefik.http.middlewares.redirect-to-canonical.redirectregex.regex=^https?://(?:{DOMAIN}|{IP}|127\\.0\\.0\\.1)(.*)"
      # - "traefik.http.middlewares.redirect-to-canonical.redirectregex.replacement=https://${DOMAIN}$$1}"
      # - "traefik.http.middlewares.redirect-to-canonical.redirectregex.permanent=true"


      # - "traefik.http.services.noop-service.loadbalancer.server.url=http://127.0.0.1"

  # pebble:
  #   image: letsencrypt/pebble
  #   container_name: pebble
  #   hostname: pebble
  #   environment:
  #     - PEBBLE_VA_NOSLEEP=1
  #   ports:
  #     - "14000:14000" # Pebble ACME server
  #     - "15000:15000" # Pebble challenge server
  #   networks:
  #     - backend
  #   labels:
  #     - "traefik.enable=true"