entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    exposedByDefault: false

# self certificates
# tls:
#   certificates:
#     - certFile: "/etc/traefik/certs/cert.pem"
#       keyFile: "/etc/traefik/certs/key.pem"
# acme let's encrypt certificates
certificatesResolvers:
  myresolver:
    acme:
      email: "${ADMIN_EMAIL}"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "websecure"
log:
  level: DEBUG
accessLog: {}
global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  dashboard: true
  # insecure: true
