secrets:
  ssl_key:
    file: ${NGINX_KEY}
  ssl_cert:
    file: ${NGINX_CERT}

volumes:
  nginx-logs:
    driver: local
    name: nginx-vol
    driver_opts:
      type: bind
      o: bind
      device: ${NGINX_VOL}

  dns-logs:
    driver: local
    # name: dns-vol
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${NGINX_VOL}

networks:
  internal:
    driver: bridge
    name: internal
  dns-tier:
    name: dns-tier
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
#   host_network:
#     external:
#       name: host

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        HOST_USER: ${HOST_USER}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: nginx
    # user: ${USER_ID}:${GROUP_ID}
    image: nginx
    hostname: nginx
    secrets:
      - ssl_key
      - ssl_cert
    volumes:
      - ${NGINX_VOL}:/usr/share/nginx/html
    ports:
      - $NGINX_PORT:$NGINX_PORT
    environment:
      DOMAIN: ${DOMAIN}
      HOST_USER: ${HOST_USER}
      NGINX_PORT: ${NGINX_PORT}
      IP: ${IP}
    # depends_on:
    #   wordpress:
    #     condition: service_healthy
    networks:
      - dns-tier
      - internal
    #   - host_network
    restart: on-failure
    expose:
      - ${NGINX_PORT}
    healthcheck:
      test:
        ["CMD", "curl", "-fk", "https://${DOMAIN}"]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "${DOMAIN}:${IP}"
    dns:
      - ${IP}
      - 127.0.0.1
    depends_on:
      - fastify
    # labels:
    #   - "traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)"

  # dnsmasq:
  #   # build:
  #     # dockerfile: Dockerfile
  #   container_name: dnsmasq
  #   image: andyshinn/dnsmasq:2.78
  #   hostname: dnsmasq
  #   environment:
  #     DOMAIN: ${DOMAIN}
  #     IP: ${IP}
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     - "5053:53/udp"
  #   volumes:
  #     - dns-logs:/etc/dnsmasq.conf
  #     - ./DNS/conf/dnsmasq.conf:/etc/dnsmasq.conf
  #   networks:
  #     - dns-tier
  #     - internal

#   traefik:
#     image: traefik:v2.5
#     container_name: traefik
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
#     command:
#       - "--api.insecure=true"
#       - "--providers.docker=true"
#       - "--entrypoints.web.address=:80"
#     networks:
#       - dns-tier
  # dns:
  #   build:
  #     context: ./DNS/
  #   restart: always
  #   ports:
  #     - 5053:53
  #     - 5053:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   command: named -c /etc/bind/named.conf -g -u named