http:
  routers:
    user-service:
      rule: "Host(`user-service.local`)"
      service: user-service
      entryPoints:
        - web
    tournament-service:
      rule: "Host(`tournament-service.local`)"
      service: tournament-service
      entryPoints:
        - web
    matchmaking-service:
      rule: "Host(`matchmaking-service.local`)"
      service: matchmaking-service
      entryPoints:
        - web
    game-session-service:
      rule: "Host(`game-session-service.local`)"
      service: game-session-service
      entryPoints:
        - web
    frontend-service:
      rule: "Host(`frontend.local`)"
      service: frontend-service
      entryPoints:
        - web

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:8000"
    tournament-service:
      loadBalancer:
        servers:
          - url: "http://tournament-service:8000"
    matchmaking-service:
      loadBalancer:
        servers:
          - url: "http://matchmaking-service:8000"
    game-session-service:
      loadBalancer:
        servers:
          - url: "http://game-session-service:8000"
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend-service:3000"