entryPoints:
  web:
    address: ":80"
    # allowACMEByPass: true
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"
  websecure:
    address: ":443"
    allowACMEByPass: true
    http2:
      maxConcurrentStreams: 250
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: "{{ env 'DOMAIN' }}"
            sans:
              - "{{ env 'IP' }}"
            #   - "*.{{ env 'DNS_SEARCH' }}"
    forwardedHeaders:
      trustedIPs:
        - "0.0.0.0/0"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
#   file:
    # filename: /etc/traefik/etc/traefik/dynamic.yml
    # watch: true

# self certificates
tls:
  certificates:
    - certFile: "/run/secrets/ssl_crt"
      keyFile: "/run/secrets/ssl_key"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/run/secrets/ssl_crt"
        keyFile: "/run/secrets/ssl_key"
  options:
    default:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384

# acme let's encrypt certificates
certificatesResolvers:
  myresolver:
    acme:
    #   email: " lilizarr@student.42wolfsburg.de"
      email: "/run/secrets/ssl_email"
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}

log:
  level: DEBUG
accessLog: {}
global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  dashboard: false
  insecure: true