secrets:
  envFile:
    file: ${AUTH_ENV}

volumes:
  auth-vol:
    driver: local
    name: auth-vol

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DEBUG_MODE=${DEBUG_MODE:-0}
        - DNS_SERVER=8.8.8.8
    image: img_auth:latest
    container_name: auth
    hostname: auth
    volumes:
      - auth-vol:/app
    restart: unless-stopped
    secrets:
      - envFile
    env_file:
      - ${AUTH_ENV}
    environment:
      NODE_ENV: development
      DOMAIN: ${DOMAIN}
      IP: ${IP}
      ENV_FILE_PATH: /run/secrets/envFile
      DEBUG_MODE: ${DEBUG_MODE:-0}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    expose:
      - "3001"
    networks:
      backend:
        ipv4_address: 172.18.0.2
    labels:
    - "traefik.enable=true"

    # --- Public Router: Externally facing ---
    # Matches any request coming to the public domain with the /api/auth prefix
    - "traefik.http.routers.api-auth-public.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/auth`)"
    - "traefik.http.routers.api-auth-public.entrypoints=websecure"
    - "traefik.http.routers.api-auth-public.tls=true"
    - "traefik.http.routers.api-auth-public.priority=300"
    # Apply middlewares: one for Host rewriting and one for path rewriting
    - "traefik.http.routers.api-auth-public.middlewares=change-host-to-auth,rewrite-auth-path"
    - "traefik.http.middlewares.change-host-to-auth.headers.customrequestheaders.Host=auth.${DOMAIN}"
    # Middleware: Rewrite the incoming path. Strips the /api/auth prefix so that:
    #   /api/auth/login  →  /api/login
    - "traefik.http.middlewares.rewrite-auth-path.replacePathRegex.regex=^/api/auth(.*)"
    - "traefik.http.middlewares.rewrite-auth-path.replacePathRegex.replacement=/api$1"
    # - "traefik.http.routers.api-auth-internal.middlewares=auth-ip-whitelist"
    # - "traefik.http.middlewares.auth-ip-whitelist.ipwhitelist.sourcerange=172.18.0.0/24"
    # Service Definition: auth microservice backend
    - "traefik.http.services.auth-service.loadbalancer.server.port=3001"


  # - "traefik.http.middlewares.api-headers.headers.accesscontrolallowmethods=GET,POST,OPTIONS"