secrets:
  envFile:
    file: ${AUTH_ENV}

volumes:
  authentication-vol:
    driver: local
    name: authentication-vol
    # driver_opts:
    #   type: bind
    #   o: bind
    #   device: ./

# networks:
#   backend:
#     external: true

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DNS_SERVER=8.8.8.8
    image: img_authentication:latest
    container_name: auth
    hostname: auth
    volumes:
      - authentication-vol:/usr/src/app
    # working_dir: /usr/src/app
    restart: unless-stopped
    secrets:
      - envFile
    env_file:
      - ${AUTH_ENV}
    environment:
      NODE_ENV: development
      DOMAIN: ${DOMAIN}
      IP: ${IP}
      DOMAIN_TEST: ${DOMAIN_TEST}
      ENV_FILE_PATH: /run/secrets/envFile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - backend
    labels:
        - "traefik.enable=true"
        # --- Public Router: Externally facing ---
        # Matches any request coming to the public domain with the /api/auth prefix
        - "traefik.http.routers.api-auth-public.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/auth`)"
        - "traefik.http.routers.api-auth-public.entrypoints=websecure"
        - "traefik.http.routers.api-auth-public.tls=true"
        - "traefik.http.routers.api-auth-public.priority=90"
        # Apply middlewares: one for Host rewriting and one for path rewriting
        - "traefik.http.routers.api-auth-public.middlewares=change-host-to-auth,rewrite-auth-path"
        # Middleware: Change the Host header to the internal hostname (auth.domain)
        - "traefik.http.middlewares.change-host-to-auth.headers.customrequestheaders.Host=auth.${DOMAIN}"
        # Middleware: Rewrite the incoming path. Strips the /api/auth prefix so that:
        #   /api/auth/login  →  /api/login
        - "traefik.http.middlewares.rewrite-auth-path.replacePathRegex.regex=^/api/auth(.*)"
        - "traefik.http.middlewares.rewrite-auth-path.replacePathRegex.replacement=/api$1"
        # --- Internal Router ---
        # This router allows internal microservices to call the auth service directly using auth.domain
        - "traefik.http.routers.api-auth-internal.rule=Host(`auth.${DOMAIN}`) && PathPrefix(`/api`)"
        - "traefik.http.routers.api-auth-internal.entrypoints=websecure"
        - "traefik.http.routers.api-auth-internal.tls=true"
        - "traefik.http.services.authentication-service.loadbalancer.server.port=3001"

