secrets:
  envFile:
    file: ${AUTH_ENV}

volumes:
  authentication-vol:
    driver: local
    name: authentication-vol
    # driver_opts:
    #   type: bind
    #   o: bind
    #   device: ./

# networks:
#   backend:
#     external: true

services:
  authentication:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DNS_SERVER=8.8.8.8
    image: img_authentication:latest
    container_name: authentication
    hostname: authentication
    volumes:
      - authentication-vol:/usr/src/app
    # working_dir: /usr/src/app
    restart: unless-stopped
    secrets:
      - envFile
    env_file:
      - ${AUTH_ENV}
    environment:
      NODE_ENV: development
      DOMAIN: ${DOMAIN}
      IP: ${IP}
      DOMAIN_TEST: ${DOMAIN_TEST}
      ENV_FILE_PATH: /run/secrets/envsecret
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentication-router.rule=Host(`${DOMAIN}`) && Path(`/api/login`)"
      - "traefik.http.routers.authentication-router.entrypoints=websecure"
      # - "traefik.http.routers.authentication-router.tls.certresolver=myresolver"
      # - "traefik.http.routers.default-redirect.middlewares=redirect-to-https@file"
      # - "traefik.http.routers.https-redirect.middlewares=redirect-to-canonical@file"
      - "traefik.http.services.authentication-service.loadbalancer.server.port=3001"
